language: ruby
rvm:
  - 2.5.3

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --only-4xx --assume-extension --check-html --allow-hash-href

cache:
  directories:
  - $TRAVIS_BUILD_DIR/tmp/.htmlproofer #https://github.com/gjtorikian/html-proofer/issues/381
  
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
