# Site settings
title:            BIMstandards
description:      Bonnes pratiques des standards openBIM, pour des échanges opérationnels au quotidien !
keywords:         standards, BIM, openBIM, interopérabilité, BuildingSMART, IFC, IDM, MVD, COBie, BCF, bSDD, gbXML, BIMétré
author:           Alexandre Grignon
url:              "http://bimstandards.fr"
repository:       bimstandards/bimstandards

# Versions
version:          v0.1.0-beta.5
latest_update:    18/05/2016

# Build settings
markdown:         kramdown
highlighter:      rouge
exclude:          [vendor]

# Collections
collections:
  pages: {output: true, permalink: '/:path/'}
  standards: {output: true, permalink: '/standards/:path/'}
  bonnes-pratiques: {output: true, permalink: '/bonnes-pratiques/:path/'}
  archicad: {output: true, permalink: '/archicad/:path/'}
  ressources: {output: true, permalink: '/ressources/:path/'}
  
# Assets
sass:
  style: compressed
cdn:
  css:            https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css
  js:             https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.js
  jquery:         https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js

# Gems (Jekyll plugins)
gems:
  - jekyll-sitemap
  - jekyll-github-metadata

# Pour activer github-metadata : https://github.com/jekyll/github-metadata
# $ JEKYLL_GITHUB_TOKEN=123abc [bundle exec] jekyll serve
